apiVersion: kubeshare.nthu/v1
kind: SharePod
metadata:
  name: sharepod1
  annotations:
    "kubeshare/gpu_request": "0.5"
    "kubeshare/gpu_limit": "1.0"
    "kubeshare/gpu_mem": "3145728000"
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: cuda
    image: nvidia/cuda:11.6.1-base-ubuntu20.04 
    imagePullPolicy: Always
    command: ["sh", "-c", "sleep infinity"]
